apiVersion: apps/v1
kind: Deployment
metadata:
  name: fourthcoffee-app
  namespace: fourthcoffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fourthcoffee-app
  template:
    metadata:
      labels:
        app: fourthcoffee-app
    spec:
      containers:
      - name: fourthcoffee
        image: bcacr.azurecr.io/fourthcoffeepos:latest
        ports:
        - containerPort: 5000
        env:
        - name: DBHOST
          value: my-db
        - name: DBNAME
          value: fourthcoffeedb
        - name: HEAD_TITLE
          value: "El Jarocho"
        - name: DBENABLED
          value: "True"
        - name: SEASON
          value: "Winter"
        - name: DBUSER
          value: root
        - name: DBSECRET
          value: Microsoft2022
---
apiVersion: v1
kind: Service
metadata:
  name: fourthcoffee-app
  namespace: fourthcoffee
  labels:
    app: fourthcoffee-app
spec:
  type: LoadBalancer
  selector:
    app: fourthcoffee-app
  ports:
  - name: http
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db
  namespace: fourthcoffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: db
        image: bcacr.azurecr.io/fourthcoffeedb/fourthcoffeedb:latest
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-vol
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-vol
          hostPath:
            path: /var/mysql-data
---
apiVersion: v1
kind: Service
metadata:
  name: my-db
  namespace: fourthcoffee
spec:
  selector:
    app: my-db
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
