# Postgre SQL Service
apiVersion: v1
kind: Service
metadata:
  name: contosodb
  namespace: contoso
spec:
  selector:
    app: contosodb
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
---
# Create PostgreSQL Database Container with local storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosodb
  namespace: contoso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosodb
  template:
    metadata:
      labels:
        app: contosodb
    spec:
      containers:
      - name: contosodb
        image: postgres:15.0
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: secret
        - name: POSTGRES_DB
          value: contoso
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgresql-vol
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-vol
          hostPath:
            path: /var/postgresql-data