# Create Contoso Supermarket Point Of Sale Service
apiVersion: v1
kind: Service
metadata:
  name: contosopos
  namespace: contoso
  labels:
    app: contosopos
spec:
  selector:
    app: contosopos
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
# Create Contoso Supermarket Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contosopos
  namespace: contoso
  labels:
    app: contosopos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contosopos
  template:
    metadata:
      labels:
        app: contosopos
    spec:
      containers:
        - name: contosopos
          image: jumpstartagora.azurecr.io/contoso-supermarket/pos:latest
          env:
            - name: SQL_HOST
              value: contosodb
            - name: SQL_USERNAME
              value: postgres
            - name: SQL_PASSWORD
              value: secret     
            - name: SQL_DATABASE
              value: contoso
            - name: HEAD_TITLE
              value : "Contoso Supermarket"
            - name: CAMERAS_ENABLED
              value: "False"
            - name: CAMERAS_BASEURL
              value: ""
            - name: NEW_CATEGORY
              value: "True"
            - name: STORE_ID
              value: "2"
            - name: STORE_LOCATION
              value: "Redmond"
            - name: HOLIDAY_BANNER
              value: "False"
          ports:
            - containerPort: 5000