apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-sql-file
  namespace: contoso
data:
  initDB.sql: "initdb.sql"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: contoso
spec:
  template:
    metadata:
      name: init-db
    spec:
      containers:
      - name: initdb
        image: postgres:15.0
        env:
        - name: PGHOST
          value: contosodb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: secret
        - name: PGPASSWORD
          value: secret      
        - name: POSTGRES_DB
          value: contoso
        command:
          - sh
          - -c
          - psql -h $PGHOST -U $POSTGRES_USER -d $POSTGRES_DB -f /var/initdb.sql
        volumeMounts:
          - name: init-db-sql
            mountPath: /var/initdb.sql
            subPath: initDB.sql
      restartPolicy: "Never"
      volumes:
        - name: init-db-sql
          configMap:
            name: init-db-sql-file
            items:
            - key: initDB.sql
              path: initDB.sql
        
